### ISSUE TITLE
PowerShell process exit after execution of Java Main-Class.

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/KNet#104]
During the test this particular behavior was highlighted: the Java Main-Class does not returns control to the cmdlet, but PowerShell process exit.

_Originally posted by @masesdevelopers in https://github.com/masesgroup/KNet/issues/100#issuecomment-1295261590_

**Comment by masesdevelopers** [comment]
Working with KNetCLI and trying to reproduce the issue there, the same behavior happens on KNetCL: the process exit and Main-Class does not return the control to the calling process. The test was done using ConsoleConsumer class.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers this is a snippet of the class you used:

```scala
  def main(args: Array[String]): Unit = {
    val conf = new ConsumerConfig(args)
    try {
      run(conf)
    } catch {
      case e: AuthenticationException =>
        error("Authentication failed: terminating consumer process", e)
        Exit.exit(1)
      case e: Throwable =>
        error("Unknown error when running consumer: ", e)
        Exit.exit(1)
    }
  }
```

If there is any exception the class invokes `Exit.exit(1)`, and this is captured from the operating system and propagated to the hosting process which is _pwsh.exe_ in this case. _KNetCLI.exe_ is a process, like _pwsh_, and it receives the `exit` command, but it was launched from another process (e.g. cmd.exe) that remains alive.

In this case we have another actor in the middle: it is the JVM. @masesdevelopers verify if:
- the receiving actor is the JVM or the hosting process
- it is possible to inject an hook in the first receiving actor

Otherwise, to avoid that main _pwsh.exe_ exit, verify if it is possible to create a child process which executes the job using the stdin, stdout, stderr of the host.

**Comment by masesdevelopers** [comment]
> 
> _KNetCLI.exe_ is a process, like _pwsh_, and it receives the `exit` command, but it was launched from another process (e.g. cmd.exe) that remains alive.
> 
@mariomastrodicasa you are right: _KNetCLI.exe_ exits with a return code of 1.

**Comment by masesdevelopers** [comment]
> Otherwise, to avoid that main _pwsh.exe_ exit, verify if it is possible to create a child process which executes the job using the stdin, stdout, stderr of the host.

@mariomastrodicasa will be implemented the child process.

**Comment by masesdevelopers** [comment]
JNet 1.4.12 solves this issue, but inputs from PowerShell main instance are not sent to Main-Class.
