### ISSUE TITLE
Unable to find org.apache.kafka.clients.CommonClientConfigs

### ISSUE THREAD

**Issue by AntonyLittle** [masesgroup/KNet#188]
**Describe the bug**
When attempting to run the `KNetBenchmark` test, using the commandline `dotnet run -Server localhost:29092`, I receive the following error:
```
The type initializer for 'MASES.KNet.Clients.CommonClientConfigs' threw an exception.
Unable to find org.apache.kafka.clients.CommonClientConfigs
```

**To Reproduce**
1. Clone the KNet source
2. Change directory to `KNet/tests/KNetBenchmark`
3. Enter `dotnet run -Server localhost:29092`

**Expected behavior**
Test should execute

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version 22.04

**Additional context**
The issue appears to be tied to the use of custom serdes when creating a producer in the test code - creating producers that use the default string serdes for key and value does not cause this problem.

**Comment by AntonyLittle** [comment]
My apologies, using default serdes produces the exact same behaviour :(

**Comment by masesdevelopers** [comment]
Hi @AntonyLittle, from your description seems an important step is missing: you have to build the Java sources, which downloads the Maven artifacts too. Currently there aren't instructions for the generation from scratch, however the following comes from the workflows YAML (to complete the steps you must install Maven):
- Clone the KNet source into `KNetRoot` (use the name of your convenience)
- Change directory to `KNetRoot`
- Execute a first compilation with the following command to restore some dependencies:
```bash
dotnet build --no-incremental --configuration Release /p:Platform="Any CPU" src/net/KNet/KNet.csproj
```
- Execute the following Maven command to create a pseudo Maven artifact (this is for KNet 1.5.5):
```bash
mvn install:install-file -DgroupId=JCOBridge -DartifactId=JCOBridge -Dversion=2.5.7 -Dpackaging=jar -Dfile=../../../bin/net6.0/JCOBridge.jar -f ./src/java/knet/pom.xml
```
- Execute the following Maven command to build and copy the needed JARs:
```bash
mvn --file ./src/java/knet/pom.xml --no-transfer-progress package
```
- Ended previous step you have a new folder named `jars` under `KNetRoot`
- At this point executing the command `dotnet run -Server localhost:29092` under `KNetRoot/tests/KNetBenchmark` the JARs within `KNetRoot/jars` will be copied under `KNetRoot/bin/<RID_Folder>` (e.g. RID_Folder can be net6.0) and will be available to the JVM for class identification
  - if the previous does not happens just copy the content of `KNetRoot/jars` under `KNetRoot/bin/<RID_Folder>/jars`, maybe this folder is already available because a dependency of KNet (JNet) uses the the same pattern
- KNet is instructed to search for Java classes in JARs available under a subfolder named `jars` and the class `org.apache.kafka.clients.CommonClientConfigs` will be found

**NOTE**: KNet version 1.5.5 uses artifacts of Apache Kafka 3.4.0

**Comment by AntonyLittle** [comment]
Excellent, that works, thank you :)
