### ISSUE TITLE
Link documentation

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#24]
**Is your feature request related to a problem? Please describe.**
The documentation available on website under docs folder does not have any reference to the official Apache Kafka Javadocs.

**Describe the solution you'd like**
Try to find a solution to cross-link the documentation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
First version of JNet Reflector (see masesgroup/JNet#45) comes with an initial stub of code generation which links the documentation. When the tool will cover more features the documentation can be created using an automatic tool.

**Comment by masesdevelopers** [comment]
Many warning are raised because the following line report https://github.com/masesgroup/KNet/blob/3a72d0441fe53426b8337b8410f61223fec31594/src/net/KNet/Generated/Kafka/Admin/DeleteRecordsCommand.cs#L48 while the parameter is https://github.com/masesgroup/KNet/blob/3a72d0441fe53426b8337b8410f61223fec31594/src/net/KNet/Generated/Kafka/Admin/DeleteRecordsCommand.cs#L49

The worst case happens for parameters like https://github.com/masesgroup/KNet/blob/3a72d0441fe53426b8337b8410f61223fec31594/src/net/KNet/Generated/Kafka/Admin/BrokerMetadata.cs#L55 it contains `$`

**Comment by masesdevelopers** [comment]
https://github.com/masesgroup/KNet/issues/24#issuecomment-1624495285 still not closed, reopen issue
