### ISSUE TITLE
Unexpected `Java.Lang.NullPointerException` raised 

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/KNet#242]
The snippet code where the exception is raised is:
```java
    private Future<RecordMetadata> doSend(ProducerRecord<K, V> record, Callback callback) {
        // Append callback takes care of the following:
        //  - call interceptors and user callback on completion
        //  - remember partition that is calculated in RecordAccumulator.append
        AppendCallbacks<K, V> appendCallbacks = new AppendCallbacks<K, V>(callback, this.interceptors, record);

        try {
            throwIfProducerClosed();
            // first make sure the metadata for the topic is available
            long nowMs = time.milliseconds();
            ClusterAndWaitTime clusterAndWaitTime;
            try {
                clusterAndWaitTime = waitOnMetadata(record.topic(), record.partition(), nowMs, maxBlockTimeMs);
            } catch (KafkaException e) {
                if (metadata.isClosed())
                    throw new KafkaException("Producer closed while send in progress", e);
                throw e;
            }
```
in particular on the line `clusterAndWaitTime = waitOnMetadata(record.topic(), record.partition(), nowMs, maxBlockTimeMs);`. In that point the `ProducerRecord<K, V>` in input is accessed to get both `topic` and `partition`.

The `record` object is created inline within the 
```
Future<RecordMetadata> Send(KNetProducerRecord<K, V> record)
{
    ProducerRecord<byte[], byte[]> kRecord = ToProducerRecord(record, _keySerializer, _valueSerializer);
    return Send(kRecord);
}
```

Currently, since the full call chain is synchronous till that point and within the Java code, the idea is that the `record` (`kRecord` in .NET) object was retired from the Garbage Collector because between .NET and Java (JVM) the code shares the JNI pointer.

_Originally posted by @masesdevelopers in https://github.com/masesgroup/KEFCore/issues/66#issuecomment-1746745415_

**Comment by mariomastrodicasa** [comment]
Looking to the point of exception reported I found that https://github.com/masesgroup/KNet/blob/3da64a3524be6ff6e7a6bc21419545ffc1cb5b36/src/net/KNet/Specific/Consumer/KNetConsumer.cs#L278 manages the pattern of https://github.com/masesgroup/KNet/issues/242#issuecomment-1746758562. @masesdevelopers option 1 can be applied to the developed code, option 2 needs an update of JNetReflector, needs more CPU and maybe the code does not obtain improvements because most of the objects are not retired from GC due to some GC root.

Meanwhile I found that this line https://github.com/masesgroup/KNet/blob/3da64a3524be6ff6e7a6bc21419545ffc1cb5b36/src/net/KNet/Specific/Replicator/KNetCompactedReplicator.cs#L823 reports an exception slightly different (_partition cannot be `null`_), however its root cause can be the same analyzed here.
